// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Slides$ReactTemplate = require("./Slides.bs.js");

var slideSeparator = "\n---\n";

var slideContentSeparator = "\n\n";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Slides$ReactTemplate.make(/* :: */[
              /* [] */0,
              /* [] */0
            ], true, /* array */[])), "index1");

fetch("slide-content.md").then((function (prim) {
              return prim.text();
            })).then((function (text) {
            return Promise.resolve($$Array.to_list(text.split(slideSeparator)));
          })).then((function (slideArray) {
          return Promise.resolve(List.map((function (slide) {
                            return $$Array.to_list(slide.split(slideContentSeparator));
                          }), slideArray));
        })).then((function (slideContent) {
        return Promise.resolve(ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Slides$ReactTemplate.make(slideContent, false, /* array */[])), "index1"));
      }));

exports.slideSeparator = slideSeparator;
exports.slideContentSeparator = slideContentSeparator;
/*  Not a pure module */
