// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Slides$ReactTemplate = require("./Slides.bs.js");

var content = /* :: */[
  /* :: */[
    "# Slide 1",
    /* :: */[
      "Subcontent 1",
      /* [] */0
    ]
  ],
  /* :: */[
    /* :: */[
      "# Slide 2",
      /* [] */0
    ],
    /* :: */[
      /* :: */[
        "# Slide 3",
        /* :: */[
          "_Subcontent_ 1",
          /* :: */[
            "**Subcontent** 2",
            /* :: */[
              "## Subcontent 3",
              /* :: */[
                "Subcontent 4",
                /* [] */0
              ]
            ]
          ]
        ]
      ],
      /* [] */0
    ]
  ]
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Slides$ReactTemplate.make(content, /* array */[])), "index1");

exports.content = content;
/*  Not a pure module */
