// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Showdown = require("showdown");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TianyupuHighlightJs = require("tianyupu-highlight.js");

function setMarkdownRef(theRef, param) {
  param[/* state */1][/* markdownRef */1][0] = (theRef == null) ? undefined : Caml_option.nullable_to_opt(theRef.querySelector("pre code"));
  return /* () */0;
}

var component = ReasonReact.reducerComponent("Markdown");

function make(markdown, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var match = self[/* state */1][/* converter */0][0];
              if (match !== undefined) {
                Caml_option.valFromOption(match).setFlavor("github");
              }
              var match$1 = self[/* state */1][/* markdownRef */1][0];
              if (match$1 !== undefined) {
                TianyupuHighlightJs.highlightBlock(Caml_option.valFromOption(match$1));
                return /* () */0;
              } else {
                return /* () */0;
              }
            }),
          /* didUpdate */(function (oldAndNewSelf) {
              var match = oldAndNewSelf[/* newSelf */1][/* state */1][/* markdownRef */1][0];
              if (match !== undefined) {
                TianyupuHighlightJs.highlightBlock(Caml_option.valFromOption(match));
                return /* () */0;
              } else {
                return /* () */0;
              }
            }),
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* converter */0][0];
              if (match !== undefined) {
                return React.createElement("div", {
                            ref: Curry._1(self[/* handle */0], setMarkdownRef),
                            dangerouslySetInnerHTML: {
                              __html: Caml_option.valFromOption(match).makeHtml(markdown)
                            }
                          });
              } else {
                return null;
              }
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* converter : record */[/* contents */Caml_option.some(new Showdown.Converter())],
                      /* markdownRef : record */[/* contents */undefined]
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_action, _state) {
              return /* NoUpdate */0;
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.setMarkdownRef = setMarkdownRef;
exports.component = component;
exports.make = make;
/* component Not a pure module */
