// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("SlideControls");

var controlsStyle = {
  bottom: "20px",
  position: "fixed",
  right: "10px"
};

function leftControlStyle(controlsColor) {
  return {
          backgroundColor: "transparent",
          border: "12px solid transparent",
          borderRightColor: controlsColor,
          borderRightWidth: "22px",
          cursor: "pointer",
          margin: "0 5px 0 5px",
          padding: "0"
        };
}

function rightControlStyle(controlsColor) {
  return {
          backgroundColor: "transparent",
          border: "12px solid transparent",
          borderLeftColor: controlsColor,
          borderLeftWidth: "22px",
          cursor: "pointer",
          margin: "0 5px 0 5px",
          padding: "0"
        };
}

function make(controlsColor, prevCallback, nextCallback, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("aside", {
                          style: controlsStyle
                        }, React.createElement("button", {
                              style: leftControlStyle(controlsColor),
                              onClick: (function (_event) {
                                  return Curry._1(prevCallback, /* () */0);
                                })
                            }), React.createElement("button", {
                              style: rightControlStyle(controlsColor),
                              onClick: (function (_event) {
                                  return Curry._1(nextCallback, /* () */0);
                                })
                            }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.controlsStyle = controlsStyle;
exports.leftControlStyle = leftControlStyle;
exports.rightControlStyle = rightControlStyle;
exports.make = make;
/* component Not a pure module */
